# Generated by Django 5.2.17 on 2026-10-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('observables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseobservable',
            name='observable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_observables', to='observables.observable'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casestatus'),
        ),
        migrations.AddField(
            model_name='casecustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_values', to='cases.customfield'),
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cases', to='cases.tag'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.case'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.case'),
        ),
        migrations.AddConstraint(
            model_name='caseobservable',
            constraint=models.UniqueConstraint(fields=('case', 'observable'), name='uniq_case_observable'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', '-start_date'], name='case_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-severity'], name='case_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assignee'], name='case_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['number'], name='case_number_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-created_at'], name='case_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['case'], name='task_case_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='task_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['case', '-date'], name='timeline_case_date_idx'),
        ),
    ]
