"""REVIEW-2026-10-03 hardening for the `cases` app.

* **C1** `Case.number` becomes `AllocatedNumberField(unique=True, editable=False)`. The
  type is unchanged but the class is not: the value is allocated by the field's
  `pre_save` (a Postgres sequence via `nextval`, `MAX(number)+1` on SQLite), which is the
  only hook every INSERT path runs — `bulk_create()` never calls `save()`.
* **M1** seven redundant indexes removed. Three hand-written indexes duplicated an
  implicit FK index or the `unique=True` index on `number` (`case_assignee_idx`,
  `case_number_idx`, `task_case_idx`); six FK columns are left-prefix-covered by a
  composite or unique index and get `db_index=False`. Every one is justified inline in
  `cases/models.py`.
* **M5** explicit reverse-direction indexes on the observable link tables, so AGENTS.md
  Module C's `observable -> cases` fan-out cannot silently depend on an implicit index.
* **M9** timeline index gains a trailing `-id`, making keyset pagination deterministic
  when automation events share microsecond precision.
* **M4** `(case, custom_field)` uniqueness on custom-field values.
* **M6** `db_table` `case` -> `case_record`; `case` is a reserved SQL word and Phase 8
  writes raw SQL.
* **H5/L1** `choices` + CHECK constraints on `Case.severity/tlp/pap`, `Task.status`,
  `CaseStatus.stage`, `CustomField.type`.
* **L5** `Case.start_date` becomes NOT NULL with a default: on Postgres
  `ORDER BY start_date DESC` sorts NULLs first, so undated cases would top the queue.
* **L4** `closed_date` is stamped on the transition into the Closed stage (model code).
"""

# Generated by Django 5.2.17 on 2026-10-03 15:43

import cases.numbering
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_seed'),
        ('identity', '0003_identity_hardening'),
        ('observables', '0002_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='case',
            name='case_assignee_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='case_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_case_idx',
        ),
        migrations.RemoveIndex(
            model_name='timelineevent',
            name='timeline_case_date_idx',
        ),
        migrations.AlterField(
            model_name='case',
            name='number',
            field=cases.numbering.AllocatedNumberField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='pap',
            field=models.SmallIntegerField(choices=[(0, 'White'), (1, 'Green'), (2, 'Amber'), (3, 'Red')], default=2),
        ),
        migrations.AlterField(
            model_name='case',
            name='severity',
            field=models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casestatus'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tlp',
            field=models.SmallIntegerField(choices=[(0, 'White'), (1, 'Green'), (2, 'Amber'), (3, 'Red'), (4, 'Unknown')], default=2),
        ),
        migrations.AlterField(
            model_name='casecustomfieldvalue',
            name='case',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='casecustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='case_values', to='cases.customfield'),
        ),
        migrations.AlterField(
            model_name='caseobservable',
            name='case',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='case_observables', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='caseobservable',
            name='observable',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='case_observables', to='observables.observable'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='stage',
            field=models.CharField(choices=[('New', 'New'), ('InProgress', 'InProgress'), ('Closed', 'Closed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date'), ('url', 'url')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], default='Waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='case',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.case'),
        ),
        migrations.AddIndex(
            model_name='caseobservable',
            index=models.Index(fields=['observable', 'case'], name='caseobs_obs_case_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['case', '-date', '-id'], name='timeline_case_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('severity__gte', 1), ('severity__lte', 4)), name='case_severity_range'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('tlp__gte', 0), ('tlp__lte', 4)), name='case_tlp_range'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('pap__gte', 0), ('pap__lte', 3)), name='case_pap_range'),
        ),
        migrations.AddConstraint(
            model_name='casecustomfieldvalue',
            constraint=models.UniqueConstraint(fields=('case', 'custom_field'), name='uniq_case_custom_field'),
        ),
        migrations.AddConstraint(
            model_name='casestatus',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ('New', 'InProgress', 'Closed'))), name='case_status_stage_valid'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ('string', 'integer', 'float', 'boolean', 'date', 'url'))), name='custom_field_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('Waiting', 'InProgress', 'Completed', 'Cancel'))), name='task_status_valid'),
        ),
        migrations.AlterModelTable(
            name='case',
            table='case_record',
        ),
    ]
