# Generated by Django 5.2.17 on 2026-10-04 08:55
#
# REVIEW-2026-10-04 round-2 **H-5** (TODO 1.15) — `M1` over-pruned. The `db_index=False`
# on `CaseCustomFieldValue.custom_field` was justified by "the unique constraint below is a
# left prefix for each", but `custom_field` is the constraint's **right-hand** column:
#
#     uniq_case_custom_field(case_id, custom_field_id)
#                      ^^^^ left prefix          ^^^^^^^^^^^^ not covered
#
# Measured plan before the fix (`EXPLAIN QUERY PLAN`, 400 rows):
#     WHERE case_id       = ?   -> SEARCH ... USING sqlite_autoindex (case_id=?)
#     WHERE custom_field_id = ? -> SCAN case_custom_field_value          <-- seq scan
#
# `AlterField` (not `AddIndex`) because this restores Django's implicit FK index, which is
# what `db_index=True` emits — the column's index is the thing that was lost.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_number_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_values', to='cases.customfield'),
        ),
    ]