# Generated by Django 5.2.17 on 2026-10-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_casetaglink_alter_case_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseobservable',
            name='updated_at',
        ),
    ]
