# Generated by Django 5.2.17 on 2026-10-09 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_remove_alertobservable_updated_at'),
        ('cases', '0008_remove_caseobservable_updated_at'),
        ('identity', '0003_identity_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('alert', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='alerts.alert')),
                ('case', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
                'indexes': [models.Index(fields=['case', '-created_at', '-id'], name='comment_case_created_idx'), models.Index(fields=['alert', '-created_at', '-id'], name='comment_alert_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('alert__isnull', True), ('case__isnull', False)), models.Q(('alert__isnull', False), ('case__isnull', True)), _connector='OR'), name='comment_one_parent')],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('case', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'page',
                'indexes': [models.Index(fields=['case', 'order', 'created_at'], name='page_case_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.JSONField(default=dict)),
                ('case', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shares', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_shares', to='identity.organisation')),
            ],
            options={
                'db_table': 'share',
                'constraints': [models.UniqueConstraint(fields=('case', 'organisation'), name='uniq_share_case_org')],
            },
        ),
    ]
