# Generated by Django 5.2.17 on 2026-10-09 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_comment_page_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=255)),
                ('external', models.BooleanField(default=False)),
                ('case', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachment',
                'indexes': [models.Index(fields=['case', '-created_at', '-id'], name='attach_case_created_idx'), models.Index(fields=['sha256'], name='attach_sha256_idx')],
            },
        ),
    ]
