# Generated by Django 5.2.17 on 2026-10-09 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('title_prefix', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('severity', models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('tlp', models.SmallIntegerField(choices=[(0, 'White'), (1, 'Green'), (2, 'Amber'), (3, 'Red'), (4, 'Unknown')], default=2)),
                ('pap', models.SmallIntegerField(choices=[(0, 'White'), (1, 'Green'), (2, 'Amber'), (3, 'Red')], default=2)),
                ('flag', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'case_template',
                'constraints': [models.CheckConstraint(condition=models.Q(('severity__gte', 1), ('severity__lte', 4)), name='case_template_severity_range'), models.CheckConstraint(condition=models.Q(('tlp__gte', 0), ('tlp__lte', 4)), name='case_template_tlp_range'), models.CheckConstraint(condition=models.Q(('pap__gte', 0), ('pap__lte', 3)), name='case_template_pap_range')],
            },
        ),
    ]
