# Generated by Django 5.2.17 on 2026-10-09 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_remove_alertobservable_updated_at'),
        ('cases', '0011_casetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ttp_code', models.CharField(blank=True, default='', max_length=64)),
                ('tactic', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ttp',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occur_date', models.DateTimeField(blank=True, null=True)),
                ('pattern_id', models.CharField(blank=True, default='', max_length=255)),
                ('pattern_name', models.CharField(blank=True, default='', max_length=255)),
                ('tactic', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('alert', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='alerts.alert')),
                ('case', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='cases.case')),
                ('ttp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='cases.ttp')),
            ],
            options={
                'db_table': 'procedure',
                'indexes': [models.Index(fields=['case', 'occur_date'], name='procedure_case_date_idx'), models.Index(fields=['alert', 'occur_date'], name='procedure_alert_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('alert__isnull', True), ('case__isnull', False)), models.Q(('alert__isnull', False), ('case__isnull', True)), _connector='OR'), name='procedure_exactly_one_parent')],
            },
        ),
    ]
