# Generated by Django 5.2.17 on 2026-10-09 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_ttp_procedure'),
        ('identity', '0003_identity_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['ingestion_warnings'], name='case_ingestion_warnings_gin', opclasses=['gin_jsonb_ops']),
        ),
    ]
