# Generated by Django 5.2.17 on 2026-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_add_gin_indexes_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseobservable',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
