# Generated by Django 5.2.17 on 2026-10-03 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mapping_config', models.JSONField(blank=True, default=dict)),
                ('default_severity', models.SmallIntegerField(default=2)),
                ('correlation_enabled', models.BooleanField(default=True)),
                ('webhook_secret_hash', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'ingestion_source',
            },
        ),
    ]
