"""REVIEW-2026-10-03 hardening for `IngestionSource`.

**H5/L1** `default_severity` gains `choices` (DRF-level validation, so AC2.5's
out-of-range -> 400 has something to enforce) and a CHECK constraint (database-level, so
a raw write is refused too). Severity is the same 1..4 contract everywhere it appears.
"""

# Generated by Django 5.2.17 on 2026-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionsource',
            name='default_severity',
            field=models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2),
        ),
        migrations.AddConstraint(
            model_name='ingestionsource',
            constraint=models.CheckConstraint(condition=models.Q(('default_severity__gte', 1), ('default_severity__lte', 4)), name='ingestion_source_severity_range'),
        ),
    ]
