# Generated by Django 5.2.17 on 2026-10-03 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservableType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_attachment', models.BooleanField(default=False)),
                ('is_case_sensitive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'observable_type',
            },
        ),
        migrations.CreateModel(
            name='Observable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.TextField()),
                ('normalized_data', models.TextField()),
                ('ioc', models.BooleanField(default=False)),
                ('sighted', models.BooleanField(default=False)),
                ('sighted_at', models.DateTimeField(blank=True, null=True)),
                ('ignore_similarity', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('tlp', models.SmallIntegerField(default=2)),
                ('pap', models.SmallIntegerField(default=2)),
                ('enrichment_data', models.JSONField(blank=True, default=dict)),
                ('external', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='observables', to='cases.tag')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observables', to='observables.observabletype')),
            ],
            options={
                'db_table': 'observable',
                'indexes': [models.Index(fields=['-created_at'], name='obs_created_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('data_type', 'normalized_data'), name='uniq_obs_dtype_norm')],
            },
        ),
    ]
