# Generated by Django 5.2.17 on 2026-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0005_rehash_observable_data_hash'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='observable',
            index=models.Index(fields=['enrichment_data'], name='obs_enrichment_data_gin', opclasses=['gin_jsonb_ops']),
        ),
    ]
