# Generated by Django 5.2.17 on 2026-10-03 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('value', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'alert_custom_field_value',
            },
        ),
        migrations.CreateModel(
            name='AlertObservable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alert_observable',
            },
        ),
        migrations.CreateModel(
            name='AlertStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=64, unique=True)),
                ('stage', models.CharField(max_length=32)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'alert_status',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('source_ref', models.CharField(max_length=255)),
                ('external_link', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('severity', models.SmallIntegerField(default=2)),
                ('date', models.DateTimeField()),
                ('flag', models.BooleanField(default=False)),
                ('tlp', models.SmallIntegerField(default=2)),
                ('pap', models.SmallIntegerField(default=2)),
                ('summary', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('follow', models.BooleanField(default=False)),
                ('ingestion_warnings', models.JSONField(blank=True, default=dict)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert',
            },
        ),
    ]
