# Generated by Django 5.2.17 on 2026-10-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('cases', '0001_initial'),
        ('identity', '0002_organisation_alter_apikey_user_alter_user_org'),
        ('ingest', '0001_initial'),
        ('observables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='cases.case'),
        ),
        migrations.AddField(
            model_name='alert',
            name='owner_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='identity.organisation'),
        ),
        migrations.AddField(
            model_name='alert',
            name='source_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ingest.ingestionsource'),
        ),
        migrations.AddField(
            model_name='alert',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='cases.tag'),
        ),
        migrations.AddField(
            model_name='alertcustomfieldvalue',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='alertcustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_values', to='cases.customfield'),
        ),
        migrations.AddField(
            model_name='alertobservable',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_alert_observables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertobservable',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_observables', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='alertobservable',
            name='observable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_observables', to='observables.observable'),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.alertstatus'),
        ),
        migrations.AddConstraint(
            model_name='alertobservable',
            constraint=models.UniqueConstraint(fields=('alert', 'observable'), name='uniq_alert_observable'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-date'], name='alert_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['case'], name='alert_case_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='alert_created_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('source', 'type', 'source_ref'), name='uniq_alert_source_type_ref'),
        ),
    ]
