"""REVIEW-2026-10-03 hardening for the `alerts` app.

* **M2** `Alert.source_id` renamed to `Alert.ingestion_source`. The old field name
  generated the column `source_id_id`, which every raw query in the correlation engine
  would have had to know about. `RenameField` keeps the data; on Postgres it is a plain
  `ALTER TABLE ... RENAME COLUMN`, on SQLite a table rebuild.
* **M3** the `source` (verbatim wire string) / `ingestion_source` (our FK) split is
  documented on the model and is deliberate: they must never be derived from one another.
* **C3** no schema change: the unconditional unique `(source, type, source_ref)` stays.
  The fix is that the pipeline always populates `source_ref` — `ingest/references.py`
  synthesises `sha256:<digest of the canonicalised payload>` and records the
  substitution in `ingestion_warnings`.
* **C4** `correlation_key` (namespaced, e.g. `dest_ip:10.0.0.5`) plus a
  `(correlation_key, date)` index. AC5.2's query previously compiled to JSON extraction
  over `raw_payload` with a temp b-tree; it is now an index seek on both engines.
* **M1** `alert_case_idx` removed (duplicates the implicit FK index); `Alert.status`
  gets `db_index=False` (left prefix of `alert_status_date_idx`).
* **M4** `(alert, custom_field)` uniqueness. **M5** reverse link index.
* **H5/L1** `choices` + CHECK constraints on severity/tlp/pap and `AlertStatus.stage`.
* **L5** `Alert.date` becomes NOT NULL with a default for the same NULLS-FIRST reason.
"""

# Generated by Django 5.2.17 on 2026-10-03 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_seed'),
        ('cases', '0002_initial'),
        ('identity', '0003_identity_hardening'),
        ('ingest', '0002_ingestion_source_hardening'),
        ('observables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='alert_case_idx',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='source_id',
            new_name='ingestion_source',
        ),
        migrations.AddField(
            model_name='alert',
            name='correlation_key',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='alert',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alert',
            name='pap',
            field=models.SmallIntegerField(choices=[(0, 'White'), (1, 'Green'), (2, 'Amber'), (3, 'Red')], default=2),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.alertstatus'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='tlp',
            field=models.SmallIntegerField(choices=[(0, 'White'), (1, 'Green'), (2, 'Amber'), (3, 'Red'), (4, 'Unknown')], default=2),
        ),
        migrations.AlterField(
            model_name='alertcustomfieldvalue',
            name='alert',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='alerts.alert'),
        ),
        migrations.AlterField(
            model_name='alertcustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='alert_values', to='cases.customfield'),
        ),
        migrations.AlterField(
            model_name='alertobservable',
            name='alert',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='alert_observables', to='alerts.alert'),
        ),
        migrations.AlterField(
            model_name='alertobservable',
            name='observable',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='alert_observables', to='observables.observable'),
        ),
        migrations.AlterField(
            model_name='alertstatus',
            name='stage',
            field=models.CharField(choices=[('New', 'New'), ('InProgress', 'InProgress'), ('Closed', 'Closed'), ('Imported', 'Imported')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['correlation_key', 'date'], name='alert_corrkey_date_idx'),
        ),
        migrations.AddIndex(
            model_name='alertobservable',
            index=models.Index(fields=['observable', 'alert'], name='alertobs_obs_alert_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(('severity__gte', 1), ('severity__lte', 4)), name='alert_severity_range'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(('tlp__gte', 0), ('tlp__lte', 4)), name='alert_tlp_range'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(condition=models.Q(('pap__gte', 0), ('pap__lte', 3)), name='alert_pap_range'),
        ),
        migrations.AddConstraint(
            model_name='alertcustomfieldvalue',
            constraint=models.UniqueConstraint(fields=('alert', 'custom_field'), name='uniq_alert_custom_field'),
        ),
        migrations.AddConstraint(
            model_name='alertstatus',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ('New', 'InProgress', 'Closed', 'Imported'))), name='alert_status_stage_valid'),
        ),
    ]
