# Generated by Django 5.2.17 on 2026-10-04 08:55
#
# The alerts-side twin of `cases/migrations/0006_restore_custom_field_fk_indexes.py` —
# REVIEW-2026-10-04 round-2 **H-5** (TODO 1.15). Same over-pruning, same fix:
# `uniq_alert_custom_field(alert_id, custom_field_id)` has `custom_field_id` on the right,
# so `WHERE custom_field_id = ?` was a sequential scan until this migration restored the
# implicit FK index. Kept as a separate file so `alerts` and `cases` migrations can be
# applied independently.
#
# On the dependency list: this migration touches only the `alerts` app's own model. Its
# target, `cases.customfield`, has existed since `cases/0001_initial` and is not altered by
# `cases/0006`, so `cases/0002_initial` — where `AlertCustomFieldValue.custom_field` was
# added — is the newest `cases` state this file actually needs.
#
# It deliberately does **not** depend on `cases/0006`. A dependency is an ordering promise,
# and Django honours it in reverse: it forces `cases/0006` to be unapplied whenever anything
# rolls `cases` back. That is what broke `test_seed_migrations.py`, which unapplies
# `cases/0003_seed` on SQLite — a path where `observables/0003` and `alerts/0004` already
# cannot be reversed cleanly. The extra unapply left `alert` pointing at a `case_record`
# table that the rollback had already renamed away, and every subsequent teardown flush
# failed with `no such table: main.case_record`. The index fix does not need that coupling.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_hardening'),
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertcustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_values', to='cases.customfield'),
        ),
    ]