# Generated by Django 5.2.17, then hand-adjusted.
#
# On the dependency list: an A/B experiment on this commit (round-3 **H3-2**) established that
# pinning `observables/0002_seed` instead of the leaf `observables/0004` makes **no** difference to
# what gets unapplied. Rolling `observables` back to `0001_initial` drops the same 13 migrations
# either way, and drops `case_record` either way. The dependency is therefore retained at
# `observables/0002_seed` because it is the newest state these models genuinely require — the two
# `AlertObservable` FKs were last altered in `alerts/0004_alert_hardening`, and
# `observables/0004` touches `ObservableTagLink` only, not this file's models. An earlier comment
# here claimed the pin prevented a `case_record` cascade; that was wrong, and it is retracted rather
# than left standing because it read as a safety guarantee it never provided.
#
# The real situation, per round-3 §H3-2, is that the seed-rollback tests exercise a path where
# `observables/0003` and `alerts/0004` cannot be reversed cleanly, so `test_seed_migrations.py`
# fails loudly on SQLite (`no such table: main.case_record`) under **either** pin. That is a
# genuine gap tracked in TODO, not something this file can fix by choosing a different parent.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_alertcustomfieldvalue_alert_and_more'),
        ('observables', '0002_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertobservable',
            name='alert',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='alert_observables', to='alerts.alert'),
        ),
        migrations.AlterField(
            model_name='alertobservable',
            name='observable',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='alert_observables', to='observables.observable'),
        ),
    ]
