# Generated by Django 5.2.17 on 2026-10-05 04:55

# Generated by Django 5.2.17, then hand-adjusted.
#
# On the dependency list: this migration touches only `alerts`' own models, so it depends only
# on the newest `observables` state those models actually need. The two `AlertObservable` FKs
# were altered by REVIEW-2026-10-04 **L-2** in `observables/0004`, and `AlertCustomFieldValue`/
# `AlertObservable` existed since `alerts/0002_initial` -- so `observables/0002_seed` is the
# newest state required, and the leaf `observables/0004` is not.
#
# It deliberately does **not** depend on `observables/0004`. A dependency is an ordering promise
# and Django honours it in reverse: it forces `observables/0004` to be unapplied whenever anything
# rolls `observables` back. `test_seed_migrations.py` unapplies `observables/0002_seed` on SQLite,
# and the extra unapply cascaded into `cases`/`alerts`, leaving `alert` pointing at a
# `case_record` table the rollback had already renamed away -- every later teardown flush then
# failed with `no such table: main.case_record`. Same reasoning as `alerts/0005`, which pins
# `cases/0002_initial` for the same reason.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_alertcustomfieldvalue_alert_and_more'),
        ('observables', '0002_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertobservable',
            name='alert',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='alert_observables', to='alerts.alert'),
        ),
        migrations.AlterField(
            model_name='alertobservable',
            name='observable',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='alert_observables', to='observables.observable'),
        ),
    ]
