# Generated by Django 5.2.17 on 2026-10-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alter_alertobservable_alert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertobservable',
            name='updated_at',
        ),
    ]
