# Generated by Django 5.2.17 on 2026-10-09 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_remove_alertobservable_updated_at'),
        ('cases', '0012_ttp_procedure'),
        ('identity', '0003_identity_hardening'),
        ('ingest', '0002_ingestion_source_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['raw_payload'], name='alert_raw_payload_gin', opclasses=['gin_jsonb_ops']),
        ),
    ]
