# Generated by Django 5.2.17 on 2026-10-09 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_add_gin_index_raw_payload'),
        ('cases', '0013_add_gin_indexes_json_fields'),
        ('identity', '0003_identity_hardening'),
        ('ingest', '0002_ingestion_source_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['ingestion_warnings'], name='alert_ingestion_warnings_gin', opclasses=['gin_jsonb_ops']),
        ),
    ]
