# Generated by Django 5.2.17 on 2026-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_add_gin_index_ingestion_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertobservable',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
