# Generated by Django 5.2.17 on 2026-10-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('cases', '0001_initial'),
        ('observables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_runs', to='cases.case'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='triggered_by_observable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_runs', to='observables.observable'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['case', '-started_at'], name='ar_case_started_idx'),
        ),
    ]
