"""REVIEW-2026-10-03 hardening for the `automation` app.

* **M14** `AutomationRun.playbook` FK (PROTECT) added. `playbook_name` stays as the
  immutable snapshot of the name at dispatch time, so renaming a playbook does not
  rewrite history in the ledger; the FK is what stops a run referencing a playbook that
  does not exist.
* **C2** the three indexes pending-run dispatch needs:
  `(celery_task_id)` for task-result reconciliation,
  `(created_at) WHERE status='Pending'` — without it the Celery beat tick is a full scan
  plus sort over a monotonically growing table on every pass (partial indexes work on
  **both** SQLite and Postgres, so this one is portable), and
  `Playbook(trigger_event, is_active)` for trigger resolution on every domain event.
* **M1** `AutomationRun.case` gets `db_index=False` (left prefix of `ar_case_started_idx`).
* **H5/L1** `choices` + CHECK constraint on `AutomationRun.status`.
"""

# Generated by Django 5.2.17 on 2026-10-03 15:43

import django.db.models.deletion
from django.db import migrations, models


def assert_no_orphan_runs(apps, schema_editor):
    """A run cannot be attributed to a playbook we do not have.

    `AutomationRun.playbook_name` used to be free text, so this migration has nothing to
    migrate: there is no defensible way to invent a `Playbook` row for a historical run.
    Pre-production this table is empty; if it is not, stop and backfill by hand rather
    than let a NOT NULL alter fail with an opaque integrity error.
    """
    AutomationRun = apps.get_model('automation', 'AutomationRun')
    orphans = AutomationRun.objects.count()
    if orphans:
        raise RuntimeError(
            f'{orphans} AutomationRun row(s) exist and cannot be given a playbook FK. '
            'Create the Playbook rows and backfill automation_run.playbook before '
            're-running this migration.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_hardening'),
        ('automation', '0002_initial'),
        ('cases', '0003_seed'),
        ('observables', '0002_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='playbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='automation.playbook'),
        ),
        migrations.RunPython(assert_no_orphan_runs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='automationrun',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='automation.playbook'),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='case',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_runs', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='automationrun',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['celery_task_id'], name='ar_celery_task_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(condition=models.Q(('status', 'Pending')), fields=['created_at'], name='ar_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='playbook',
            index=models.Index(fields=['trigger_event', 'is_active'], name='playbook_trigger_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('Pending', 'Running', 'Success', 'Failed'))), name='automation_run_status_valid'),
        ),
    ]
