# Generated by Django 5.2.17 on 2026-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_remove_alertobservable_updated_at'),
        ('automation', '0003_automation_hardening'),
        ('cases', '0012_ttp_procedure'),
        ('observables', '0005_rehash_observable_data_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='triggered_by',
            field=models.CharField(choices=[('trigger', 'Trigger'), ('manual', 'Manual')], default='trigger', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='automationrun',
            constraint=models.CheckConstraint(condition=models.Q(('triggered_by__in', ('trigger', 'manual'))), name='automation_run_triggered_by_valid'),
        ),
    ]
