# Generated by Django 5.2.17 on 2026-10-09 12:52

from django.db import migrations


def create_example_playbook(apps, schema_editor):
    """Create an example playbook for observable enrichment (plan §8, T2.5)."""
    Playbook = apps.get_model("automation", "Playbook")
    Playbook.objects.get_or_create(
        name="Enrich Observable",
        defaults={
            "description": "Example enrichment playbook that runs the local probe action on new observables.",
            "trigger_event": "observable.created",
            "is_active": True,
            "config": {
                "action": "python",
                "action_path": "amalthea.automation.executor.enrichment_probe",
            },
        },
    )


def remove_example_playbook(apps, schema_editor):
    """Remove the example playbook."""
    Playbook = apps.get_model("automation", "Playbook")
    Playbook.objects.filter(name="Enrich Observable").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_seed_playbook'),
    ]

    operations = [
        migrations.RunPython(create_example_playbook, remove_example_playbook),
    ]